// <auto-generated />
using System;
using Ecommerce.Models.config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("ISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a71762a4-e586-4d0c-a46e-4f574e7f4122",
                            ISO = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = "ca299447-7671-4da5-95cb-e98b095c3e3a",
                            ISO = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = "b79a3be6-6a24-4c47-814e-799c89e13af6",
                            ISO = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = "885a4656-ae70-4521-9f49-655f3ed371a8",
                            ISO = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = "69cd5932-d7e2-4b51-8f3d-4f8b8f78d73a",
                            ISO = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = "48b8962a-1c6e-437d-a56e-7747bb4b3009",
                            ISO = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = "4e5849c5-67a8-4f2c-8567-3f946dcba5ba",
                            ISO = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = "1472f6e9-3219-4538-9baf-9983ceca9f1f",
                            ISO = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = "cf1c8846-b17d-48b6-8bfa-30a43e0e65e4",
                            ISO = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = "ded24cdd-0088-4719-ad12-6b3c424524c5",
                            ISO = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = "d8338115-dc01-4505-ae7a-8c6bf5e02b92",
                            ISO = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = "9fc21a14-4a20-43bc-92de-4463881f4359",
                            ISO = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = "c33c7ce1-271f-4976-af76-95eb2353be78",
                            ISO = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = "32185d4b-adbc-410e-9259-c0923dbc0bad",
                            ISO = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = "a39f1af9-689a-4393-82b8-31e6981a366c",
                            ISO = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = "3e513a9e-5eb2-4541-abdb-e3ae3f3be779",
                            ISO = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = "4961e9d4-401f-40cd-a6a6-b69f42346417",
                            ISO = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = "43c30f81-850f-4299-97f9-2faa02e25b16",
                            ISO = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = "d3a313f4-60dc-4adf-b88f-eaa455518baf",
                            ISO = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = "ac9032cd-8d0a-4702-848d-5b877e08adb1",
                            ISO = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = "1aff024c-42a7-419b-9d8b-cf274f1776b8",
                            ISO = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = "7b5727ab-c754-4a03-afb1-9d6479dce066",
                            ISO = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = "4125f65a-2d75-4be9-9d22-930f2f408eb0",
                            ISO = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = "e2712547-14a6-463e-9ba8-4276f5b0f0c7",
                            ISO = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = "a3eb189e-9e9d-44da-999d-edd21094436d",
                            ISO = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = "f0a460aa-f681-4868-bad5-3794836c1f36",
                            ISO = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = "36810e74-0f22-4cb9-b124-0d389054498c",
                            ISO = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = "9e381224-b8b7-4034-9005-2172ced3989c",
                            ISO = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = "ca97822c-4aa3-41fe-9ddc-32e2e43efc81",
                            ISO = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = "81ec20b9-c797-46c0-b649-37cd655aa221",
                            ISO = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = "af75ef58-22e2-43ea-924b-363a06a17498",
                            ISO = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = "35c6c6cb-3275-4a0f-ae3a-d362b945380f",
                            ISO = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = "43f8a031-0f01-4e96-8c6b-b3c539dc3dfe",
                            ISO = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = "6d478ee6-a21d-4804-ad82-dcbc13d5367d",
                            ISO = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = "70602fa9-73c0-4d33-89c9-d392a6484950",
                            ISO = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = "5b72882f-6c78-495e-8240-939e7494d889",
                            ISO = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = "b96b71ff-63d8-47b4-9b70-0467456d8ed0",
                            ISO = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = "f0bbe063-79a3-4b9c-9d79-0c1e732c1833",
                            ISO = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = "05e0be1d-91da-43e9-80a5-f402e28b0c99",
                            ISO = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = "21a8ea71-53e9-4d7d-84f5-6d08472f28c6",
                            ISO = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = "32ce6e83-6809-4a8f-bd3c-09ca2d61cf74",
                            ISO = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = "a6e5130b-bb16-428a-bedd-56e3107474eb",
                            ISO = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = "256ae7cd-3d73-4897-934b-49391b3cf8d2",
                            ISO = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = "61210860-fff6-4508-89e4-5fae72d17a55",
                            ISO = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = "e3555c94-048d-478e-a08b-8df6a38d2c63",
                            ISO = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = "cc316bfb-2706-494f-973a-0dfe4dc420ea",
                            ISO = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = "9a61d597-d978-4c60-8c74-a0d03c9b4e12",
                            ISO = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = "f798244e-fd42-4c11-aa62-a1da94e99884",
                            ISO = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = "13d0598d-e8a6-428f-82a6-075fd9517be7",
                            ISO = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = "815b22fe-37e0-426c-a50c-a6691cc1be4a",
                            ISO = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = "ac9ce39f-94ea-4d14-ae19-289bd764333d",
                            ISO = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = "d05f9ae9-75de-4cdc-9522-4feada5e7546",
                            ISO = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = "afa3af7e-b4ba-4d6d-b9d6-ccb844ba8da2",
                            ISO = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = "c2583e33-c2b2-493d-a5e4-fb876732145a",
                            ISO = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = "172df277-c897-48a3-a97c-e3721da7760b",
                            ISO = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = "77a53a77-3101-4380-aa98-cf87c2b4f023",
                            ISO = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = "d46d68e2-0f77-4fa8-bd1a-83ca4287eeab",
                            ISO = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = "20d3059b-c608-4963-8a4a-147853603416",
                            ISO = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = "70f70990-973a-4459-8b99-3385c6190aa2",
                            ISO = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = "6fe1fe38-522b-4b15-8219-b7d55b40dafb",
                            ISO = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = "4afbb250-f42b-45ec-b873-99d9248bf620",
                            ISO = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = "6a971cd4-5ba9-4fe5-8d99-dc5e5a40bc1e",
                            ISO = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = "d39fb202-9fa9-48e8-8284-c175626f1bfb",
                            ISO = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = "814b9d27-a369-4477-8145-af1aeef458eb",
                            ISO = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = "8d42b85a-3856-41d3-bf20-e157ef21e716",
                            ISO = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = "dcce4d00-5397-4734-8e92-8026749c3954",
                            ISO = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = "5b8af243-c0f4-47f4-89ed-4135dc32d820",
                            ISO = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = "9ac08f1f-714a-4088-9603-d2ada7a00077",
                            ISO = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = "68451cd3-3ff3-492e-92df-2a20d4e36749",
                            ISO = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = "b05e965a-27e1-4b7e-acf3-5d64607a69fd",
                            ISO = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = "98fa5224-6508-4752-9f1a-46f0b52191b3",
                            ISO = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = "a6549f3a-75dd-4dd4-9478-04ab8045eea7",
                            ISO = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = "c0e493aa-095f-4153-9e97-4feb1972e21b",
                            ISO = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = "76c32d34-75cf-4a27-a9d0-550c9f0ad71f",
                            ISO = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = "6319bf4e-883b-4dc3-8217-ece4099c0ec5",
                            ISO = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = "ea6ff77a-b5f0-44f7-ba83-f66da437a988",
                            ISO = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = "dde2bf75-e2f9-404b-843e-2910944997d1",
                            ISO = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = "fb918fbe-5f39-4517-b562-fd708cf53686",
                            ISO = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = "05f02002-f6e5-4107-ad18-4a9521bda667",
                            ISO = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = "85669ac7-05f6-4195-a172-60d9b947f1ca",
                            ISO = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = "096640ae-8eaf-42f9-a54e-6649e02cd80f",
                            ISO = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = "8d7e2fe5-4fb9-4c57-affe-20cf9329dfd3",
                            ISO = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = "753d83c8-1839-421a-bae5-c94b2e6c9c36",
                            ISO = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = "e998a23b-d7cd-4652-b48d-4039444ee3ba",
                            ISO = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = "f1e8077b-2116-49d4-a9eb-86bd8bb810cb",
                            ISO = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = "3f09b082-c57c-4611-966f-020af57feb4d",
                            ISO = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = "ffc21b4b-58b5-43fe-9cbd-133b1550bca4",
                            ISO = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = "5e08b762-2e43-4ff9-952a-c729db4754f9",
                            ISO = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = "cfe5c1c1-af97-4334-a566-0256ab263dc6",
                            ISO = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = "b084e33d-3c15-4e2c-8a15-35f5ab26d786",
                            ISO = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = "a4d4c988-77f9-409d-9a2a-de71f6b134dc",
                            ISO = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = "3565baf5-a612-49d9-9706-470f4dbc2a51",
                            ISO = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = "96a86019-c2c2-4d79-9405-e96019a8be72",
                            ISO = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = "74b4813a-8dbc-4913-b2b4-a816e3a27360",
                            ISO = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = "636ea299-2435-4407-89d5-dd5526ee8b0c",
                            ISO = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = "35ecccce-7292-48ea-b828-d0c97563c64e",
                            ISO = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = "bd12b415-4113-4d55-a5e3-45299ba0ab93",
                            ISO = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = "7822c7be-a0b4-4ba3-81cf-a34b60531e49",
                            ISO = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = "c31d9229-681d-44c4-9370-c8f3f02c9779",
                            ISO = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = "49799be7-6852-4e43-92ae-4678315370c8",
                            ISO = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = "8ce3d4ab-da02-487a-8b7a-a5ce1aa4cd8a",
                            ISO = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = "4dc3933d-dcb6-4a46-89af-250da95feefa",
                            ISO = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = "0d0b5da5-8f02-4e45-8934-0b122c591d41",
                            ISO = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = "03a8b0f4-1287-4ce4-93a6-ff57a76f5a52",
                            ISO = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = "e9c41f5c-1dc8-4139-b5e9-5aadb51159da",
                            ISO = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = "a42f91e0-9c1f-453a-becf-3d0f02356632",
                            ISO = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = "d154d9d0-62fa-45d6-ad79-33b1ea8a2785",
                            ISO = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = "905dd96a-b17c-4582-85ee-e3b0ecd1e9f8",
                            ISO = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = "51e2b608-c392-4d70-af66-035286787358",
                            ISO = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = "778b93f4-f3a4-4414-a776-dd38939da03b",
                            ISO = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = "2f13c7dc-01a1-44da-8f3e-0010f834ee3a",
                            ISO = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = "b05e6f1b-ff5f-424e-9cd7-6cbea624b4f9",
                            ISO = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = "87a2c4f8-6ad9-4fe3-aa14-7a76c5287e15",
                            ISO = "LA",
                            Name = "Lao Peoples Democratic Republic"
                        },
                        new
                        {
                            Id = "35014b62-c9c0-435e-8224-63e8e4461cff",
                            ISO = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = "e64817c1-9c2f-4f8f-af15-2561d4cffefd",
                            ISO = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = "5498fcf3-9372-42b3-acb9-23dd134b0b62",
                            ISO = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = "8a6b8cb2-2977-4847-859f-d9b36a79366d",
                            ISO = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = "119287be-d27e-4cd7-848e-0847914106c2",
                            ISO = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = "89b07653-06b2-473a-bcbe-c8bd0ccfd6a3",
                            ISO = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = "fab9a026-73ed-47e8-ab16-c7cd78bfd4c3",
                            ISO = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = "f6b11df9-c3e1-43c9-aaee-5556c4ba449d",
                            ISO = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = "07d96518-3fe5-4783-a86e-32ffd790c2eb",
                            ISO = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = "005ee659-34e8-4a67-83ab-c4fb4d0487cf",
                            ISO = "MK",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = "01e42e46-3f43-47f6-bab5-888b8466c93d",
                            ISO = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = "f8c9bd12-2a96-438f-82f4-b4c0e17ae4b9",
                            ISO = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = "2370403d-0122-4998-b1c4-5a69747c3455",
                            ISO = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = "740e0346-f35f-47f1-9a09-170654197210",
                            ISO = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = "d5f7db19-21d4-4aee-a910-28f6ba68c9e7",
                            ISO = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = "270e05db-207d-4236-8432-ea85712376f8",
                            ISO = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = "01ed1ef4-8283-47a1-8702-27da06072a8e",
                            ISO = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = "cc4a3de3-9a97-4897-8cab-83c6a4909e91",
                            ISO = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = "2bfc96e4-d130-4245-99a1-77def4a6e1cc",
                            ISO = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = "297e1f7d-5170-4145-826c-fa9b2dddec64",
                            ISO = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = "e6b0b0a1-2b66-4127-a0dc-2e573cbb507e",
                            ISO = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = "e1fef3b2-9702-4183-9707-caf5b34578e0",
                            ISO = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = "53310dbe-4582-40cd-8940-0dd257239daf",
                            ISO = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = "36c15669-25ed-4ef3-9bb3-e076197bc5e1",
                            ISO = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = "3b52fe1f-003f-440a-ac4d-7fbff9f7d384",
                            ISO = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = "e8e9443b-766d-4125-b319-76c1d7cfaf3b",
                            ISO = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = "30c91c9c-02a8-4877-a0ae-c6777479e3c3",
                            ISO = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = "2a7811e9-0ba9-4426-9267-a31b13650fe5",
                            ISO = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = "30afc184-e8c3-4bbb-b5af-0a5bdc04581b",
                            ISO = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = "fc2ac6ce-38db-4c9c-b79d-521857430f7d",
                            ISO = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = "362fe2da-d2ac-4f93-8762-d3b32c6e7416",
                            ISO = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = "77bfe271-e4a0-4801-ac63-524dc4ceab05",
                            ISO = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = "6dff2f22-c846-4629-a713-bfe3a6f1895e",
                            ISO = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = "37be5078-ace7-43c1-9513-1a650c3e213c",
                            ISO = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = "8b2b5487-d0c1-43e1-a71c-54b7f0ef07fa",
                            ISO = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = "39d6c7f1-1e08-4464-b68d-d44eb390c236",
                            ISO = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = "d53479ce-b9b4-4e97-a49f-bcf4f1145234",
                            ISO = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = "d49e7626-e11e-46b0-bafb-9fd7c41f4732",
                            ISO = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = "02f7221c-f694-48df-b3ec-76385d26cd4e",
                            ISO = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = "a5124dd1-5b4d-45ae-aca0-0b628f63eace",
                            ISO = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = "914595c5-d005-4b1c-9f7a-efe8fd47e291",
                            ISO = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = "079d9f8a-575a-426f-9013-1657941d5f19",
                            ISO = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = "738e8070-c05c-414e-807a-8a0eb14bacde",
                            ISO = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = "b13ae1e1-99cd-4373-b468-b7a6f243f356",
                            ISO = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = "3f0741be-3524-4578-88a1-db617d487627",
                            ISO = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = "9d38405b-11a4-4a13-a92c-5aae2bddca5c",
                            ISO = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = "10fce04c-0bf5-491d-b9ac-39b5a37fe49d",
                            ISO = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = "150f52be-888c-4fa6-986f-b9854c333103",
                            ISO = "PS",
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = "fa5bef28-9f75-4555-98ba-4296aca9479a",
                            ISO = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = "789b2ba4-1700-4e11-9e77-58feb9ba51cd",
                            ISO = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = "18994a71-20a1-41bf-82a0-b9cc36bf1a91",
                            ISO = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = "a604bad5-eff8-41b8-bb0d-d05e0f130449",
                            ISO = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = "21ad3813-045f-42bf-b099-98ee175101ad",
                            ISO = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = "8aafc1b6-3781-4a1b-87e7-3c1dbbab4b93",
                            ISO = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = "32e7c6af-2967-4806-b652-8024f964c367",
                            ISO = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = "b4234864-ab1d-45b6-91bb-213f35bc7950",
                            ISO = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = "d6e23976-53a3-4884-abdf-f0d99d59c1f3",
                            ISO = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = "234f5461-1dd8-4ba2-8df3-676af40ef8b7",
                            ISO = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = "1df7da3b-718e-47e0-85f3-073abc1d13c4",
                            ISO = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = "5a6b94db-e823-4025-93ad-69bdaee04cdb",
                            ISO = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = "971ba193-1920-4fdb-a06a-ae5f903f0727",
                            ISO = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = "917be3e8-dbc0-4b42-894d-f11f38e4ac3d",
                            ISO = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = "fc2e4ac7-14a4-4af0-9a9f-307c66c3f307",
                            ISO = "BL",
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            Id = "66d282e8-2dfa-4701-80ce-4ff39349792c",
                            ISO = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = "f88f5254-e3b0-4a89-af20-6ae4c1f849bf",
                            ISO = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = "03ab0610-fa7e-48d5-be2f-7dc5bf7ae31e",
                            ISO = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = "9b3188b2-93a4-4339-a9ee-c522c5cbcf8b",
                            ISO = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = "75412820-c581-4b5c-abf2-dc7715d25491",
                            ISO = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = "e9c0b0e4-f2a5-4d75-8ab6-1b5a059302a3",
                            ISO = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = "480f47cd-80f8-4065-8cfd-6ccbe3bfed41",
                            ISO = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = "69ebb30e-1fe1-4a66-9137-67a46e642a74",
                            ISO = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = "1d6bebad-3e30-4528-b8a3-d80be68fc3b1",
                            ISO = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = "95614f66-58e7-4414-b192-e71225e2779c",
                            ISO = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = "c54433e9-67aa-495a-b264-ab491b3d2e2d",
                            ISO = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = "518b7e6c-285b-42ba-a3a3-204173db6ecb",
                            ISO = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = "8be3d17c-497b-4b62-b344-7267f0485f88",
                            ISO = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = "c264cb9e-ab8e-4c25-ac00-c1cec8355e74",
                            ISO = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = "24668804-652b-4747-9dfa-a7e44bb30023",
                            ISO = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = "ab2e0f91-3999-45c4-9e4b-5c7d8052d5b6",
                            ISO = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = "a4234729-48aa-4c13-a74a-efb0b06a5230",
                            ISO = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = "420d750c-2b9a-43a7-9824-067d4ea04095",
                            ISO = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = "30a8b8d5-4018-4f25-a109-57a8c689d4b1",
                            ISO = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = "9e29aae5-dfee-48ad-8504-c762a70acea7",
                            ISO = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = "0e846ecb-4963-4440-ad5d-51fddcfc1b77",
                            ISO = "GS",
                            Name = "South Georgia"
                        },
                        new
                        {
                            Id = "371197d7-aab2-4cce-a709-bea1bbe591b8",
                            ISO = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = "d1fca792-0105-4504-a0e1-fa166d183302",
                            ISO = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = "3de1faeb-8980-45c3-ae8f-ca9e3beb95b3",
                            ISO = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = "0a2e4377-7172-43da-8362-14e66bf9a537",
                            ISO = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = "b3110d1f-9bc6-4175-acc1-b3826c3f98be",
                            ISO = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = "f83e3617-83d1-4ad6-ac0a-d06720fff5eb",
                            ISO = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = "e900579a-9f12-409e-810b-1bb9a51f7be7",
                            ISO = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = "70aad067-d99a-4468-a482-9ae9d1f9f73e",
                            ISO = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = "78c38aaf-6be9-4af1-be16-817e7f9cc89a",
                            ISO = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = "4110ffe1-1167-4d45-b796-d26fd58cc479",
                            ISO = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = "43ec8874-0eed-4ab6-84c0-9cb4b6ab43b6",
                            ISO = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = "b2bfc083-5e9c-4a7c-bd42-7968ca302595",
                            ISO = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = "bec28109-949b-4eef-b699-20ae6d4aaae4",
                            ISO = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = "189c57c3-86c6-4772-b6be-b8e11c1e7f49",
                            ISO = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = "2f2a0c0e-2ca3-40d9-90f5-04e306820589",
                            ISO = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = "f695d665-1ee7-4405-b858-12d9632ec4d4",
                            ISO = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = "1c5fd123-b7a5-4f7c-9176-fd4022f8d469",
                            ISO = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = "3b83bdfc-996c-42e8-ac3f-f9a73d45d829",
                            ISO = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = "1da2394c-9f21-4572-8200-445bdc785997",
                            ISO = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = "351849ee-0531-4d02-a1ec-d8240662ea09",
                            ISO = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = "4ba370fb-6149-4f17-87a6-55c29e5f7d70",
                            ISO = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = "be5e9e81-f78b-49fd-be1d-bad0b82ce572",
                            ISO = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = "6923d723-8301-401e-827e-5ed843578320",
                            ISO = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = "cfe48571-8714-418c-80fb-61bc99e252ec",
                            ISO = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = "92b004b6-06a1-427c-85ce-7c3d86f4ca09",
                            ISO = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = "0af2d290-fe9f-40c4-8848-c671a476be05",
                            ISO = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = "8b6d728f-e3b6-4648-8e62-6a4db34559b2",
                            ISO = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = "aaeb4ebc-5fbc-4bec-9abf-77968b892bca",
                            ISO = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = "1b4dd757-552a-413c-90d6-08dbcdda7076",
                            ISO = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = "3d424576-20ec-498c-b403-4d18d9570f3e",
                            ISO = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = "4d95061b-cfb7-46b1-9100-bc6077ed3800",
                            ISO = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = "b0b4171a-da4b-4d02-904f-3a339395f53f",
                            ISO = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = "7379a55d-1342-4d4d-a56f-49aa04800d14",
                            ISO = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = "96da97d2-6de2-4aac-ab76-e6f515d02648",
                            ISO = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = "fd2af262-483e-407e-a3e2-30a5be849ed2",
                            ISO = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = "f0bfe808-f84e-4c4e-9bbf-2633711b3a35",
                            ISO = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = "c28b561b-4ede-4723-816c-5abd47836722",
                            ISO = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = "5762ddfe-cac2-46f7-bce5-5e6c59b21191",
                            ISO = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Models.UserAddress", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AddressId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Models.Address", b =>
                {
                    b.HasOne("Ecommerce.Models.Country", "Country")
                        .WithMany("Address")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Ecommerce.Models.UserAddress", b =>
                {
                    b.HasOne("Ecommerce.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Models.User", "User")
                        .WithMany("Address")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Models.Address", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("Ecommerce.Models.Country", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("Ecommerce.Models.User", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
