// <auto-generated />
using System;
using ClickMart.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickMart.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickMart.Models.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("ClickMart.Models.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ClickMart.Models.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("ISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d1b5ad94-a3c8-4fa9-8e6a-1578b2803b06",
                            ISO = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = "0c8b7068-dbe8-4de9-a8f6-71e51596ff7c",
                            ISO = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = "cbad6787-d0e5-4bd6-96b1-4a89d0f3a75d",
                            ISO = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = "3e8a8559-6d93-4ed5-8301-bba815368d6a",
                            ISO = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = "8d3438de-6d34-4040-83ed-301396e9e361",
                            ISO = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = "135f0dbc-34cb-410e-b34b-0c93feb1d735",
                            ISO = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = "5fec103d-b740-4927-a26f-1ea754944be2",
                            ISO = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = "fc2b508a-1c0c-4170-8be1-4f9e4be884cc",
                            ISO = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = "6ce43a60-8ffb-4406-a789-27499ebeaa68",
                            ISO = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = "c1a9a881-5770-431b-b88e-d7256c72fe47",
                            ISO = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = "bac6283b-51bf-428e-8b9e-7a876fc15d4e",
                            ISO = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = "733a2c51-b2ad-40bf-a4f1-f1a670d8380f",
                            ISO = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = "b0246d67-9047-4076-a5c1-8638a7820a36",
                            ISO = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = "45c61519-1c73-4955-a5c8-a3f5e1dd708d",
                            ISO = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = "b8d727b7-e3fb-4f39-857d-737bd2863d66",
                            ISO = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = "9c154140-2073-4e11-b551-a120daa8a5d3",
                            ISO = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = "dd6b9641-a290-4782-8b31-e29239abd50a",
                            ISO = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = "7599fbfd-ba38-436d-9b0d-49121141ad48",
                            ISO = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = "721f3a65-0a13-48d9-86f5-1967ceddb868",
                            ISO = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = "e2853259-5066-4748-b364-b01b37b3b6dc",
                            ISO = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = "7cc2b561-f86a-47a4-b84d-005d961ea055",
                            ISO = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = "b0a7927e-9847-4d28-b5df-46b2a5545ed2",
                            ISO = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = "12d2d2f7-20ea-4802-acc6-983b435eaca9",
                            ISO = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = "3f37733b-0408-4b8e-af30-3bfa4eafde39",
                            ISO = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = "e10840ed-1423-4baf-aaa2-f24adeec1998",
                            ISO = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = "ff0f184a-f927-435e-b6e2-8ece5bed772e",
                            ISO = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = "95557024-1d31-4762-b40d-f554d9ce35cf",
                            ISO = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = "89dde9c5-a7d7-4ce9-bfb0-e59862467c80",
                            ISO = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = "4ee0b523-f3fe-4260-9fa6-8870484a0c76",
                            ISO = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = "a2350eb6-2437-4b67-b17c-6007dab02660",
                            ISO = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = "15765f5e-28e1-4dff-b36f-f4bc55346a71",
                            ISO = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = "1f713fec-2ccd-4a65-8b12-55211c4b402c",
                            ISO = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = "8f93f051-8ba3-40a4-99f1-264501313467",
                            ISO = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = "015834bd-ff72-4216-b549-04a2a7125894",
                            ISO = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = "2b6cb908-d93b-4650-9a43-cda27410f1b5",
                            ISO = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = "a6fc340c-e47a-4441-9941-4afc002e2289",
                            ISO = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = "b933a352-ca6b-4ee6-9b06-2765395569b9",
                            ISO = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = "5201ce02-91d5-4388-9d59-e07c83c5f7e0",
                            ISO = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = "095e8e16-d1a2-48d1-a425-7e8038916bfc",
                            ISO = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = "cf3e852b-013a-47e9-97eb-1016c4830e81",
                            ISO = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = "8e0625e6-1c9c-4618-b2f3-3d8d3ed49239",
                            ISO = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = "1c56a4a3-f0dc-4a25-9fc8-16c72a116d69",
                            ISO = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = "d01b6553-2e3c-436c-bed2-fd66d7f626ce",
                            ISO = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = "d615491b-9848-41e3-857a-18e14b8d1395",
                            ISO = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = "bd092dd3-baec-4924-9e66-454df6267137",
                            ISO = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = "c832763b-5bc2-4d94-ba75-c79cc2da9baf",
                            ISO = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = "9aafd837-0419-4815-b3f7-047f189a43b8",
                            ISO = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = "1d4ea2d2-6509-460b-8bba-c21fc7cc3337",
                            ISO = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = "ab48449e-75f8-4640-a35b-e960be83b014",
                            ISO = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = "b81c5cdd-b56d-48a9-bc80-ffcb16e053b3",
                            ISO = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = "64f134ba-1eff-42ac-8424-e7f31762a009",
                            ISO = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = "e05bb8ed-0dbc-4a09-acec-e567c524bfda",
                            ISO = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = "e67f679f-9ba4-4e40-8491-018a0011b43e",
                            ISO = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = "a7474319-f6b9-4f42-9a0e-41f9a44705b4",
                            ISO = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = "8c4f57e9-3f57-4166-a26f-ff73bbcbbe73",
                            ISO = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = "dbbf7921-beca-44ca-8e40-e4c7cc8eca63",
                            ISO = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = "ced329b6-3869-4929-9869-c64cb9130451",
                            ISO = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = "563e47fc-6d91-41fb-8334-098e7dbf8f7a",
                            ISO = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = "d7b3a57c-a90b-4ab1-afae-448dc99495e9",
                            ISO = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = "44b9965f-d94f-4150-bbcc-97d1c3136a47",
                            ISO = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = "4eb621ee-a53e-40a0-a821-f68c867c5121",
                            ISO = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = "4e748e7a-7193-4d9d-b568-d06f02153067",
                            ISO = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = "dc594866-d2b1-4b66-9d32-62e0e23f08d0",
                            ISO = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = "0ce49185-8aca-4f63-9c9d-c7b17465d3e1",
                            ISO = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = "2269697f-df76-46e1-9810-6a9657352009",
                            ISO = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = "94be01f7-63da-4c9e-9577-2d8a43e1b670",
                            ISO = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = "c98a047b-5f77-4f39-9fed-73206aaa1228",
                            ISO = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = "16e9fda8-499d-47d4-8165-c474b38a6039",
                            ISO = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = "61ba700f-74e8-4ad4-b485-9bf6d8397656",
                            ISO = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = "29421b4d-dc90-4879-b657-b5acc7d8dd9a",
                            ISO = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = "472536fe-e6ff-4782-a5e8-56291f63e63c",
                            ISO = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = "7680eec5-20ca-4579-98f4-78c597741001",
                            ISO = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = "9b4cdce4-e0f9-4d5c-ae86-427b967bca88",
                            ISO = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = "adb4bf0a-e054-426b-a540-1a693c47ffa2",
                            ISO = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = "0cdb2145-b8d7-4d1a-b3fb-84a1c306fd74",
                            ISO = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = "a118fa35-8f57-4548-9c84-4df9e6cadd54",
                            ISO = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = "ba9983cf-f67c-4004-85cb-c2011d773724",
                            ISO = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = "ca5c9b8e-be6a-43e8-87fa-4b5426fe355c",
                            ISO = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = "e18dc153-c7d3-4696-9072-6fea4061f270",
                            ISO = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = "789dc390-a33a-46ee-bbe2-7f9dc92272ae",
                            ISO = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = "d89c7070-c690-4758-aff2-00be680c01c2",
                            ISO = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = "3ec118bd-44cf-445d-b6bc-44bff5950e41",
                            ISO = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = "99af4181-302b-4e38-9833-72a71ebc7385",
                            ISO = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = "902c7897-77e5-40ad-8586-cf5b15686474",
                            ISO = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = "f3fb7a0e-28af-4cab-8659-117d453dd9a1",
                            ISO = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = "5a11282b-ec6f-4381-971c-86afb979f920",
                            ISO = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = "267099f4-698a-4f69-a1f2-157ea4d0609c",
                            ISO = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = "9097e526-3049-4028-88c8-7358cb5f3e59",
                            ISO = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = "ce7d90ae-006f-423f-9221-11870a882901",
                            ISO = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = "83728bf1-79a8-493e-84be-4d9a22c56767",
                            ISO = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = "0a1988d2-c55a-4821-9abf-17dd60d52bf3",
                            ISO = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = "48caab47-5ef8-4229-be62-3cdaeab95dbb",
                            ISO = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = "c12ea6a7-d372-4b3a-b7d9-fb1990dbd7e6",
                            ISO = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = "be171361-13cc-4dbb-a34c-4726294aa9da",
                            ISO = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = "2354d156-c12e-46df-9104-96054cf40fc2",
                            ISO = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = "59ec33be-383a-4cd2-bed4-ad3d038e2d2d",
                            ISO = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = "4219566d-fee9-45d1-9dc5-b3fb1ce45e0e",
                            ISO = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = "6550e20c-139f-40aa-b1bb-c2efe910b75b",
                            ISO = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = "b91b4e39-8e2c-4752-b664-706505134642",
                            ISO = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = "c078b577-c7f0-4cd1-b353-96fef2a9fb1b",
                            ISO = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = "e01c801a-357b-4188-802c-7d51169faf76",
                            ISO = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = "5c97c35a-8320-49e4-b3e1-58f1b6b49aca",
                            ISO = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = "417358dd-3968-47c8-b2b9-d1f96580a65b",
                            ISO = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = "9dfe7913-06b7-4fb0-918a-cbe6ff4dc589",
                            ISO = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = "b556a849-8965-4b8a-b6fe-dad526f26524",
                            ISO = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = "be7cbccf-5046-4c1c-967f-f55da29e7a28",
                            ISO = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = "7c155b08-ab2e-4416-aceb-baf94b978d7a",
                            ISO = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = "ba035b15-fc44-4002-9f6e-1cb3037d2b80",
                            ISO = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = "7a1fcb5a-4258-4c35-8a47-d9fc2f2462e4",
                            ISO = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = "aef9c479-5e8f-4046-9b14-2a54f93352a8",
                            ISO = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = "96212742-f6af-4559-92de-c18aaf8d75be",
                            ISO = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = "19c447a2-929d-4ef3-b3a2-0562df8866d1",
                            ISO = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = "58d95d96-db2f-4b2c-b705-38924d49c9ec",
                            ISO = "LA",
                            Name = "Lao Peoples Democratic Republic"
                        },
                        new
                        {
                            Id = "89d92936-5d40-469f-9ff5-5ec6a22c5bf6",
                            ISO = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = "d70ce9d6-90e4-4a58-916c-5d752013749d",
                            ISO = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = "19d43b6d-1b6f-493e-a78c-aa4e2e2a16f4",
                            ISO = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = "09c49704-ddd1-4b3a-ac7e-fd6f26e1331d",
                            ISO = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = "92710c4b-aca5-4c6d-a752-38adbf6734c2",
                            ISO = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = "45b6f8b5-b552-4d66-bb67-a011beb8eb43",
                            ISO = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = "a2bbc1a8-04fc-407c-b692-8bf33f3a329c",
                            ISO = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = "dd922d1c-4199-4bf7-93da-09bbf8caa184",
                            ISO = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = "9c59167e-cc1d-43ff-99d5-1b8742d7c757",
                            ISO = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = "1da11fa4-59a3-4e96-bb81-b1ce92f10571",
                            ISO = "MK",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = "c4f597d9-7ca4-45c5-8c0a-4c79f1b67852",
                            ISO = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = "bc678375-83b3-4569-9cf2-13036560f3bc",
                            ISO = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = "4368a856-5924-4837-aed3-39a3c4a02c20",
                            ISO = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = "a1be0baf-e293-4ada-88b4-0543c544c394",
                            ISO = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = "82b1438f-83b3-4105-aab3-9f11fc53d5b1",
                            ISO = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = "42eb6060-35de-4539-aee7-18b7709a4653",
                            ISO = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = "ce858fcf-60c8-4a66-8fc1-962fdb6e3ee3",
                            ISO = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = "ab2e231b-976c-4917-875d-e9a78352a337",
                            ISO = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = "66af952d-b6d1-49f9-a1c3-6bd18c0cf9c0",
                            ISO = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = "45a6720a-695e-4794-bea0-831c911c4882",
                            ISO = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = "7c74c5ed-c331-4e61-8036-0bc3dc760856",
                            ISO = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = "1b97f403-ec01-41e9-85af-4ba13ffa1216",
                            ISO = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = "cee7a750-d7b6-41b4-8e6a-969b7d230c02",
                            ISO = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = "eff45a0f-5534-4823-9a79-add5e9a43d8e",
                            ISO = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = "74210d80-304a-456e-9505-f068f1d72c6b",
                            ISO = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = "159324ac-7292-4396-929a-2db97f3a182c",
                            ISO = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = "638f59bd-175d-4929-8b09-482a16a8669f",
                            ISO = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = "ba43da21-809f-427a-a1c8-472010ad376d",
                            ISO = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = "4d755224-3fcd-4ca9-9c45-d1d05a22481c",
                            ISO = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = "925d938e-cfe3-4916-8d7f-0ca3afada634",
                            ISO = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = "c4f51155-ca86-4e5b-b205-e192b7b180d5",
                            ISO = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = "76a7c83e-6309-41af-ac43-9f55f3e210fd",
                            ISO = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = "b73e31fc-ae07-4795-895c-ea1dbee1faff",
                            ISO = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = "84039580-415b-4d00-b702-b568312dad55",
                            ISO = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = "711d71df-0704-4eec-8840-fb6927f75aa7",
                            ISO = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = "c420bba8-dad3-431b-aa08-ee01f01553ed",
                            ISO = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = "96e3d7b9-bfe7-4111-9c36-c3d8e154cbc4",
                            ISO = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = "5fd04ac2-986e-43a7-8704-16ccabeb6676",
                            ISO = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = "5b9061ba-44a4-4d7d-92ab-45c0545ad884",
                            ISO = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = "bb041341-281f-4ae2-8b49-97ba9b3821fe",
                            ISO = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = "4c04f16d-8413-40c6-9280-f55d20bdb2c2",
                            ISO = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = "2af4a299-b355-4be1-bbdb-1dbeaab4bba7",
                            ISO = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = "6413c21a-aaac-4581-9ec4-183a30b9c09e",
                            ISO = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = "38edb94c-77cf-4278-804a-acc75c10a5da",
                            ISO = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = "8c57e853-00ef-4b43-8ed8-0a1bdb5a8065",
                            ISO = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = "9448ff53-ee3f-48b4-bcf1-03ad081a67f0",
                            ISO = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = "a191de86-b237-41e7-b8ed-6a8204245e19",
                            ISO = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = "abb9d107-04af-4f93-ae0c-030235dfbc5b",
                            ISO = "PS",
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = "01bd63f1-faf9-4f13-afc1-88016e086cc6",
                            ISO = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = "26397781-63ed-4628-9fea-8a3514a05f94",
                            ISO = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = "93b11371-a1c7-44ec-8bb5-855c200c37fd",
                            ISO = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = "430e6a32-1bca-4fc2-b5ce-555d73ab0ff6",
                            ISO = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = "51f968a4-08d3-4b41-9c8f-9f0b9a2acc7a",
                            ISO = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = "31963399-e5e8-4fb5-b30b-32ccb6392d04",
                            ISO = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = "8194b145-8d22-4163-928a-31fb29fc5b1f",
                            ISO = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = "dd0ebcb1-ab40-4a14-9a3a-040e72a899c0",
                            ISO = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = "d5a16b91-5cca-4f78-8cfb-761d705497de",
                            ISO = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = "89d93bb3-0a50-4388-94b9-0e2bda23e880",
                            ISO = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = "1a76e150-1c68-4e09-96a0-452745fd6ef4",
                            ISO = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = "f41295e7-d57f-450d-92ad-a6ec647f5aa6",
                            ISO = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = "4c1ca0b6-b34d-4462-b9c9-f1bbb5573fb1",
                            ISO = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = "0d5b4a95-40f6-4406-95ba-22d60ee19707",
                            ISO = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = "e0108940-c7f7-4885-8960-131cc4c4091e",
                            ISO = "BL",
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            Id = "9d27929d-32c7-4eda-a3ad-263a13a3d771",
                            ISO = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = "2c6b3982-6f22-45a2-baac-35e351402b4d",
                            ISO = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = "6563eee5-cc85-4160-a82e-04ddb4f9d35c",
                            ISO = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = "3fdaccc6-a1a8-4bf0-93e9-f85ad6e7d55b",
                            ISO = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = "73bf0f97-acad-46af-8426-7fb37e24fc0e",
                            ISO = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = "c1d41a3f-7925-4d30-acfb-40d944881384",
                            ISO = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = "62cc441c-004e-4c4f-b01e-9c4389a3f4f3",
                            ISO = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = "3c36b7f7-47b3-4b72-8b5c-29f45534593b",
                            ISO = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = "285e87a0-2c20-46fb-be66-c9891e022dd0",
                            ISO = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = "70c06809-92c5-4c62-bb16-f1f3b6447130",
                            ISO = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = "ebab2e5e-86d1-4910-b8fa-92113e13522d",
                            ISO = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = "d483a943-38ca-40d7-adbe-8a7b242bdca0",
                            ISO = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = "591220e9-bbca-47d9-880e-51b9228c6a3c",
                            ISO = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = "eade17b6-c109-4ae8-a380-ac78df6fefa1",
                            ISO = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = "ad0d8d40-e333-4999-b8ad-eb4d60712fd6",
                            ISO = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = "80041922-95a3-44e9-8bdc-370a4b7ff2c1",
                            ISO = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = "ce063718-69b2-457d-90e7-a4f1bd999cdf",
                            ISO = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = "5ce8721c-7d15-441e-b6a6-d452cf1672fe",
                            ISO = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = "86ccef23-42df-4d6a-921a-317980a64004",
                            ISO = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = "81ebec3d-12e5-4b52-b22e-279e50d2ceea",
                            ISO = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = "367cc4b6-0c82-40e1-ae8c-568a2b5c0fb5",
                            ISO = "GS",
                            Name = "South Georgia"
                        },
                        new
                        {
                            Id = "267b649a-94b7-4733-bcaf-6e682b88a635",
                            ISO = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = "46fccf1d-954a-4663-9b2a-cc233097e71d",
                            ISO = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = "7d010471-95f5-4823-888d-e341fe826c7d",
                            ISO = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = "2eb26d30-d27a-41f7-8c15-08bd94c33be3",
                            ISO = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = "36df9083-9620-4f2e-a8bb-c69261dee5ed",
                            ISO = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = "7738efea-b887-455b-a43a-f05ee3d51718",
                            ISO = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = "b67d7d3c-b22f-458a-b0b7-2d5ac6c4d9cc",
                            ISO = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = "ae36c87a-52ce-42c9-90be-6178b7ae2f8e",
                            ISO = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = "59154c91-4d7d-44ed-bb15-21c277706175",
                            ISO = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = "72c7ddb1-4c55-49bb-9037-0bda3e9600eb",
                            ISO = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = "1a36b0e5-712f-4583-a3d7-d28042990118",
                            ISO = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = "55fe7c83-21d1-4aa7-bf75-22346b4d8cfd",
                            ISO = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = "8bb9fe12-5c4b-40ab-9712-6ea0d9dc981c",
                            ISO = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = "29895060-96b0-4942-9157-24b1ad011050",
                            ISO = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = "292ac760-91ee-46b0-8575-1d0818aeb9fe",
                            ISO = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = "bfebdf75-04e3-49e0-8dbd-6ffb08e04752",
                            ISO = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = "82a1b8d5-9606-45db-91b2-0c38207c426c",
                            ISO = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = "c6bcecee-0e46-4b08-92e0-926bb557764b",
                            ISO = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = "4e8fe716-3e34-4420-9105-de0e168cf324",
                            ISO = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = "9fb39243-008b-4aec-8102-ec2164beb9b2",
                            ISO = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = "fd8f5281-4862-4326-a522-afbd0bf8d794",
                            ISO = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = "65a3561b-d9c1-4768-bf12-4dcce8421d01",
                            ISO = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = "27663b3a-122f-4520-ba54-459d2eb2694f",
                            ISO = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = "531615eb-257c-4412-b920-546139bc5823",
                            ISO = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = "90148e33-bd0e-4bc9-825e-77ae1f2ab024",
                            ISO = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = "a7853e93-7033-4207-b884-9fe9faf43750",
                            ISO = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = "dca7ea9d-52de-4b79-909f-3a8c35bd33d8",
                            ISO = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = "ca841d97-b21c-4634-9333-aa6cb3fd69ca",
                            ISO = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = "7843c215-c9dc-4ac8-a0eb-e5be28c4bd6c",
                            ISO = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = "1672c625-65a9-45cb-9e31-c7b9b0521fa2",
                            ISO = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = "fd240989-ec0a-463d-a80e-2b1f06deacb8",
                            ISO = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = "7a77d689-3a37-46d7-b8d4-25a75b070a18",
                            ISO = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = "ac3633e1-df1b-4af1-b4ac-b91f73289986",
                            ISO = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = "b5e623e5-50d8-4009-bb52-5ad9ef036dc4",
                            ISO = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = "e81045e9-a48c-4d18-81f3-3bf8c64679d9",
                            ISO = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = "541b18db-ba22-4d5a-8bf7-8c75bb241bd0",
                            ISO = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = "38759d5f-c323-4fff-8b80-b3b02c868d67",
                            ISO = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = "eaf902fd-f524-4b65-bde2-78e2a90f4b71",
                            ISO = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ClickMart.Models.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClickMart.Models.Models.UserAddress", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AddressId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClickMart.Models.Models.Address", b =>
                {
                    b.HasOne("ClickMart.Models.Models.Country", "Country")
                        .WithMany("Address")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ClickMart.Models.Models.UserAddress", b =>
                {
                    b.HasOne("ClickMart.Models.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickMart.Models.Models.User", "User")
                        .WithMany("Address")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClickMart.Models.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClickMart.Models.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickMart.Models.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClickMart.Models.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClickMart.Models.Models.Address", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("ClickMart.Models.Models.Country", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("ClickMart.Models.Models.User", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
